name: tanked
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_database: ^9.0.15
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  form_builder_validators: ^8.1.1
  get: ^4.6.5
  get_storage: ^2.0.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  internet_connection_checker: ^0.0.1+4
  liquid_progress_indicator: ^0.4.0
  overlay_support: ^2.0.1
  wave: ^0.2.1

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  json_annotation: null
  lint: ^1.8.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: BRFirmaBold
      fonts:
        - asset: assets/fonts/BRFirma-Bold.ttf

    - family: BRFirmaSemiBold
      fonts:
        - asset: assets/fonts/BRFirma-SemiBold.ttf

    - family: BRFirmaMedium
      fonts:
        - asset: assets/fonts/BRFirma-Medium.ttf

    - family: BRFirmaRegular
      fonts:
        - asset: assets/fonts/BRFirma-Regular.ttf

    - family: BRFirmaLight
      fonts:
        - asset: assets/fonts/BRFirma-Light.ttf

    - family: BRFirmaExtraLight
      fonts:
        - asset: assets/fonts/BRFirma-ExtraLight.ttf

    - family: BRFirmaThin
      fonts:
        - asset: assets/fonts/BRFirma-Thin.ttf
