// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX5OqvV8iozzZhwsVZelGeNXHMqlstKlQ',
    appId: '1:156930522962:web:df54e4d347227f8ab1048b',
    messagingSenderId: '156930522962',
    projectId: 'odunlade-final-year-project',
    authDomain: 'odunlade-final-year-project.firebaseapp.com',
    databaseURL: 'https://odunlade-final-year-project-default-rtdb.firebaseio.com',
    storageBucket: 'odunlade-final-year-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7RpJVkY93V1XMzo65pbVnVODhL6DLwfQ',
    appId: '1:156930522962:android:be2a0854ecd5650bb1048b',
    messagingSenderId: '156930522962',
    projectId: 'odunlade-final-year-project',
    databaseURL: 'https://odunlade-final-year-project-default-rtdb.firebaseio.com',
    storageBucket: 'odunlade-final-year-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZSJuk6Eaq2zagPky3HddsjewNl-v0wQ',
    appId: '1:156930522962:ios:8274819e7b6732a8b1048b',
    messagingSenderId: '156930522962',
    projectId: 'odunlade-final-year-project',
    databaseURL: 'https://odunlade-final-year-project-default-rtdb.firebaseio.com',
    storageBucket: 'odunlade-final-year-project.appspot.com',
    iosClientId: '156930522962-it9ie6go00slmugdolidl5rlbl8de753.apps.googleusercontent.com',
    iosBundleId: 'com.example.tanked',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZSJuk6Eaq2zagPky3HddsjewNl-v0wQ',
    appId: '1:156930522962:ios:8274819e7b6732a8b1048b',
    messagingSenderId: '156930522962',
    projectId: 'odunlade-final-year-project',
    databaseURL: 'https://odunlade-final-year-project-default-rtdb.firebaseio.com',
    storageBucket: 'odunlade-final-year-project.appspot.com',
    iosClientId: '156930522962-it9ie6go00slmugdolidl5rlbl8de753.apps.googleusercontent.com',
    iosBundleId: 'com.example.tanked',
  );
}
